fixtures:
  repositories:
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    "augeasproviders_grub": "https://github.com/hercules-team/augeasproviders_grub.git"
    "augeasproviders_core": "https://github.com/hercules-team/augeasproviders_core.git"
  symlinks:
    spectre_meltdown: "#{source_dir}"
