---
sudo: false
dist: trusty
language: ruby
cache: bundler
before_install:
  - bundle -v
  - rm Gemfile.lock || true
  - gem update --system
  - gem --version
  - bundle -v
script:
  - 'bundle exec rake $CHECK'
bundler_args: --without system_tests
rvm:
  - 2.5.3
  - 2.3.8
env:
  - PUPPET_GEM_VERSION="~> 4.0" CHECK=spec
  - PUPPET_GEM_VERSION="~> 5.0" CHECK=spec
  - PUPPET_GEM_VERSION="~> 6.0" CHECK=spec
matrix:
  fast_finish: true
  include:
    -
      bundler_args:
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
      rvm: 2.5.3
      script: bundle exec rake beaker
      services: docker
      sudo: required
    -
      env: CHECK=rubocop
    -
      env: CHECK="syntax lint"
    -
      env: CHECK=metadata_lint
    -
      rvm: 2.3.8
      script: "bundle exec rake release_checks"
notifications:
  email: false